export const BooksData = [{
        id: Math.random(),
        like: false,
        image: "https://cdn-production.frankfurtrights.com/Content/Upload/BookJackets/Thumbnails/18935283.jpg",
        rating: 4,
        name: "The Cook of Castamar",
        Author: "Fernando Muñez",
        date: "March 10, 2020",
        price: " price : 13$",
        desc: "...La cocinera de Castamar tells the story of an agoraphobic cook, at the house of a Spanish nobleman whose heart she conquers, against all odds. Clara, the main character, lives in her own small universe, the kitchen of Castamar, where the only windows to the outside world are the dishes she cooks with so much passion. But she also is an independent woman, who knows how to read and write and who lives on her own, in a world full of enemies and lies. The Duke of Castamar, on the other hand, is a young widower who lost his beloved wife in an accident, a modern man for his times… The characters of the novel are very beautifully drawn, the setting shows a tremendous amount of research. The recipes grant additional value to the book, inspiring us with lovely descriptions of the kitchen scenery, the smells and the ingredients of the dishes, very much in the style of Laura Esquivel’s Como agua para chocolate. Yet, at the same time, La cocinera de Castamar, with all its mysteries, intrigues and surprising twists, takes a new turn on sagas like Downton Abbe",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://www.babelio.com/couv/6217_451510.pjpeg",
        rating: 5,
        name: "Ce que le jour doit à la nuit",
        Author: "Yasmina Khadra",
        date: " September 12, 2012",
        price: " price : 12$",
        desc: "...After his father is unable to take care of Younes, he is sent to his uncle's house. He gets abundant love in his house and befriends Emilie, a beautiful girl.",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://images-na.ssl-images-amazon.com/images/I/512GWVheQiL._SX301_BO1,204,203,200_.jpg",
        rating: 4,
        name: "Retournez les fusils ! ",
        Author: "Jean Ziegler",
        date: " October12, 1981",
        price: " price : 7$",
        desc: "...A QUOI SERT UN INTELLECTUEL  ,LINEGALITE PARMI LES HOMMES, LES ERREMENTS DES IDEOLOGIES ,SCIENCE ET IDEOLOGIE ,ILS ONT MIS LES CHAINES A LA RACINE DE NOS TETES ,LETAT,LA NATION,COMMENT NAIT ET SE PRODUIT LA SOCIETE ?,LES PEUPLES DU SILENCE",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://64.media.tumblr.com/68d1ae5ade1a64a99fea0131d15b505e/tumblr_nemwpvSgH11qev7n1o1_1280.jpg",
        rating: 5,
        name: "The Castle",
        Author: "Franz Kafka",
        price: " price : 7.5$",
        date: "1926",
        desc: "...Left unfinished by Kafka in 1922 and not published until 1926, two years after his death, The Castle is the haunting tale of K.’s relentless, unavailing struggle with an inscrutable authority in order to gain access to the Castle. Scrupulously following the fluidity and breathlessness of the sparsely punctuated original manuscript, Mark Harman’s new translation reveals levels of comedy, energy, and visual power, previously unknown to English language readers.",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://www.guillaumemusso.com/sites/default/files/images/livres/5637207-656x1024.jpg",
        rating: 4,
        name: "Central Park",
        Author: " Guillaume Musso",
        date: "March 27, 2014",
        price: " price : 8$",
        desc: "...CENTRAL PARK CommanderTélécharger central-park-sample.pdf Alice and Gabriel have no memory of the night before…yet they won’t forget it any­time soon.New York, 8am. Alice, a young Parisian cop and Gabriel, American jazz pianist, wake up on a bench in Central park hand­cuffed to one another. They don’t know each other and have no memory of having met. The night before, Alice was at a party with her girl­friends on the Champs-Elysées and Gabriel was playing piano in a club in Dublin.",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://ellettres.files.wordpress.com/2016/01/de287-unevie.jpg",
        rating: 2,
        name: "UNE VIE ",
        Author: " Guy de Maupassant",
        date: "1883",
        price: " price : 6$",
        desc: "...Jeanne, fille du baron Simon-Jacques Le Perthuis des Vauds et de sa femme Adélaïde, est une aristocrate qui, à ses dix-sept ans, quitte le couvent. Elle s'en va donc de chez elle ; ses parents lui lèguent le château Les Peuples pour y vivre. Elle rencontre le vicomte Julien de Lamare quelques jours après sa sortie du couvent. Ils se marient et partent en voyage de noces en Corse. Très vite, à leur retour, Julien trompe Jeanne avec sa domestique Rosalie, qui tombe enceinte, puis avec la voisine Gilberte de Fourville qui se disait amie de Jeanne.",
    },

    {
        id: Math.random(),
        like: true,
        image: "https://d3525k1ryd2155.cloudfront.net/f/110/430/9780140430110.OL.0.m.jpg",
        rating: 3,
        name: "Jane Eyre",
        Author: "Charlotte Brontë",
        date: "October 16, 1847",
        price: "price : 7$",
        desc: "...Orphaned as a child, Jane has felt an outcast her whole young life. Her courage is tested once again when she arrives at Thornfield Hall, where she has been hired by the brooding, proud Edward Rochester to care for his ward Adèle. Jane finds herself drawn to his troubled yet kind spirit. She falls in love. Hard.But there is a terrifying secret inside the gloomy, forbidding Thornfield Hall. Is Rochester hiding from Jane? Will Jane be left heartbroken and exiled once again?",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://images-na.ssl-images-amazon.com/images/I/51QzQbz6MNL.jpg",
        rating: 3,
        name: "L'Étranger",
        Author: "Albert Camus",
        date: "1942",
        price: " price : 12$",
        desc: "...Condamné à mort, Meursault. Sur une plage algérienne, il a tué un Arabe. À cause du soleil, dira-t-il, parce qu'il faisait chaud. On n'en tirera rien d'autre. Rien ne le fera plus réagir : ni l'annonce de sa condamnation, ni la mort de sa mère, ni les paroles du prêtre avant la fin. Comme si, sur cette plage, il avait soudain eu la révélation de l'universelle équivalence du tout et du rien.",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://m.media-amazon.com/images/I/41ogY1y1smL.jpg",
        rating: 3,
        name: "Hamlet",
        Author: " William Shakespeare",
        date: " 1603",
        price: " price : 4$",
        desc: "...The Tragedy of Hamlet, Prince of Denmark, often shortened to Hamlet, is a tragedy written by William Shakespeare sometime between 1599 and 1601. It is Shakespeare's longest play, with 29,551 words. Set in Denmark, the play depicts Prince Hamlet and his revenge against his uncle, Claudius, who has murdered Hamlet's father in order to seize his throne and marry Hamlet's mother.",
    },

    {
        id: Math.random(),
        like: true,
        image: "https://images-na.ssl-images-amazon.com/images/I/611QYs1zFrL.jpg",
        rating: 3,
        name: "The Horla",
        Author: " Guy de Maupassant",
        price: "  price : 5$",
        date: " 1887",
        desc: "...This chilling tale of one man’s descent into madness was published shortly before the author was institutionalized for insanity, and so The Horla has inevitably been seen as informed by Guy de Maupassant’s mental illness. While such speculation is murky",
    },
    {
        id: Math.random(),
        like: true,
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386434016i/19264666.jpg",
        rating: 3,
        name: "The Strange Journey of Mr. Daldry",
        Author: "Marc Levy",
        date: " April 21, 2011",
        price: "  price : 9$",
        desc: "...Alice ;a creator of perfumes. She is passionate about her work and her only distraction from her job is her motley group of friends, who convene for late night soirees in her apartment–;much to the annoyance of her cantankerous neighbor Mr. Daldry. On Christmas Eve 1950, something happens that will change Alice's life forever: during an outing to Brighton with her friends, a fortune teller makes a mysterious prediction about Alice's future. Alice has never believed in soothsayers but she cannot stop thinking about the old woman's words.",
    },
];